version: "3.7"

services:

  dagyter:
    container_name: ${COMPOSE_PROJECT_NAME}_dagy
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "3000"
    ports:
        - "${DAGSTER_PORT}:3000"
        - "${JUPYTER_PORT}:8888"
        - "${DAGY_PORT}:8080"
        - "${STREAMLIT_PORT}:8501"
    volumes:
        - ${WORKSPACE_DIR}:/workspace
        - ${DAGSTER_PERSISTANCE_DIR}:/dagster_db/
        - ./dagster:/opt/dagster/conf
        - ./jupyter/jupyter_lab_config.py:/root/.jupyter/jupyter_server_config.py
        - ./jupyter/jupyter_lab_config.py:/root/.jupyter/jupyter_notebook_config.py
        - ./wrapper:/wrapper
        - ./.env:/wrapper/environment_settings
        - ~/.ssh:/root/.ssh:ro

