version: "3.7"

services:

  dagyter:
    container_name: ${COMPOSE_PROJECT_NAME}_dagy
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
        - ${WORKSPACE_DIR}:/workspace
        - ${DAGSTER_PERSISTANCE_DIR}:/dagster_db/
        - ~/.ssh:/root/.ssh:ro

