version: "3.7"

services:

  dagyter:
    container_name: ${COMPOSE_PROJECT_NAME}_dagy
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
        - ${WORKSPACE_DIR}:/workspace
        - ${DAGSTER_PERSISTANCE_DIR}:/dagster_db/
          #- ./dagster:/opt/dagster/conf
          #- ./jupyter/jupyter_lab_config.py:/root/.jupyter/jupyter_server_config.py
          #- ./jupyter/jupyter_lab_config.py:/root/.jupyter/jupyter_notebook_config.py
        - ~/.ssh:/root/.ssh:ro

