[pipeline1]
notebooks = ["./p1/step1.ipynb", "./p1/step2.ipynb", "./p1/step3.ipynb"]
schedule_days = "1,30,monday"
time = "21:59"

[pipeline2]
notebooks = ["./p2/p2step1.ipynb", "./p2/p2step3.ipynb"]
schedule_days = "tuesday, 8"
time = "21:59"

